// Tutorial data — IJCAI 2026
window.TUTORIAL_DATA = {
  meta: {
    venue: "IJCAI 2026",
    city: "Bremen, Germany",
    dates: "August 15–17, 2026",
    length: "Half day · 3 hours 30 minutes",
    format: "Two 1.5-hour sessions with a 30-minute break",
  },
  presenters: [
    {
      name: "Connor Lawless",
      affiliation: "Stanford University",
      email: "lawlessc@stanford.edu",
      link: "https://conlaw.github.io/",
      blurb: "Human-Centered AI postdoctoral researcher at Stanford. PhD in Operations Research (Cornell). Works at the intersection of machine learning, computational optimization, and HCI.",
    },
    {
      name: "Fei Liu",
      affiliation: "University of Zurich · ETH Zurich",
      email: "fei.liu2@uzh.ch",
      link: "#",
      blurb: "Researcher focused on evolutionary computation, LLMs for algorithm design, and automated heuristic discovery. Lead author on EoH and related methods.",
    },
    {
      name: "Hanzhang Qin",
      affiliation: "National University of Singapore",
      email: "hzqin@nus.edu.sg",
      link: "#",
      blurb: "Operations research faculty working on optimization, revenue management, and the application of large language models to large-scale optimization workflows.",
    },
    {
      name: "Ellen Vitercik",
      affiliation: "Stanford University",
      email: "vitercik@stanford.edu",
      link: "https://vitercik.github.io/",
      blurb: "Assistant Professor at Stanford (MS&E / CS). Schmidt Sciences AI2050 Early Career Fellow and NSF CAREER awardee. Works at the interface of machine learning and discrete optimization.",
    },
  ],
  schedule: [
    {
      id: "intro",
      part: "Part 1",
      title: "Introduction",
      duration: "15 min",
      minutes: 15,
      speaker: "All",
      blurb: "A broad overview of mathematical optimization, centered on mixed integer linear programming (MILP) as a core AI and OR technique.",
      bullets: [
        "The optimization pipeline: understand → formulate → tune → validate.",
        "Where current bottlenecks lie, and where LLMs can help.",
        "Framing the two halves of the tutorial: copilot + discovery.",
      ],
    },
    {
      id: "formulation",
      part: "Part 2",
      title: "Optimization Model Formulation",
      duration: "45 min",
      minutes: 45,
      speaker: "Lawless",
      blurb: "Translating informal problem descriptions into precise optimization models — a central bottleneck for domain experts without formal training in optimization.",
      bullets: [
        "Agentic frameworks: OptiMUS, LEAN-LLM-OPT, Chain-of-Experts, MCTS-based approaches.",
        "Fine-tuned models specialized for optimization: ORLM, LLM-OPT.",
        "Benchmark datasets: textbook-style, synthetic, and real-world collections such as IndustryOR.",
      ],
    },
    {
      id: "evaluation",
      part: "Part 3",
      title: "Optimization Model Evaluation",
      duration: "30 min",
      minutes: 30,
      speaker: "Lawless",
      blurb: "How do we know a generated formulation actually solves the right problem? Recent frameworks for assessing correctness and equivalence.",
      bullets: [
        "Graph-isomorphism-based approaches (Xing et al., 2024).",
        "Execution-based accuracy metrics (AhmadiTeshnizi et al., 2024).",
        "EquivaMap: formal equivalence checking (Zhai et al., 2025).",
      ],
    },
    {
      id: "break",
      part: "Break",
      title: "Coffee Break",
      duration: "30 min",
      minutes: 30,
      speaker: null,
      blurb: null,
      bullets: [],
    },
    {
      id: "solving",
      part: "Part 4",
      title: "Optimization Model Solving",
      duration: "45 min",
      minutes: 45,
      speaker: "Vitercik",
      blurb: "Modern solvers (Gurobi, CPLEX) expose many configuration parameters whose tuning is time-consuming even for experts. Can LLMs help?",
      bullets: [
        "LLMs leveraging documentation, code, and prior research for cold-start configuration.",
        "Contrast with traditional data-driven configuration methods.",
        "Strengths, limitations, and open challenges in deployment.",
      ],
    },
    {
      id: "discovery",
      part: "Part 5",
      title: "Algorithmic Discovery with LLMs",
      duration: "45 min",
      minutes: 45,
      speaker: "Liu",
      blurb: "LLMs as a new paradigm for automating algorithm design — lowering the barrier to entry and exploring design spaces hard to navigate manually.",
      bullets: [
        "A taxonomy: LLM as optimizer · extractor · predictor · designer.",
        "Methods: EoH, ReEvo, Llamea, HSEvo, MEoH, MLES.",
        "Applications across combinatorial optimization, black-box optimization, ML, and scientific discovery.",
        "Open challenges: domain LLMs, benchmarking, human–AI collaboration.",
      ],
    },
  ],
  objectives: [
    "Understand the core optimization pipeline and where LLMs can intervene.",
    "Survey the state of the art in LLM-based auto-formulation, from prompting to fine-tuning to agentic systems.",
    "Reason about correctness and equivalence for LLM-generated optimization models.",
    "Recognize how LLMs can assist solver configuration without large training datasets.",
    "Map the taxonomy of LLM-driven algorithmic discovery and its open research directions.",
  ],
  audiences: [
    {
      tag: "AI researchers",
      blurb: "Graduate students and researchers with little or no formal background in optimization.",
    },
    {
      tag: "OR researchers",
      blurb: "Optimization and operations research researchers curious about how LLMs can assist modeling and algorithm design.",
    },
    {
      tag: "Practitioners",
      blurb: "Builders of AI-enabled decision-support systems in logistics, planning, scheduling, and resource allocation.",
    },
  ],
  prerequisites: [
    "Basic mathematical maturity (variables, constraints, functions).",
    "General exposure to modern AI / machine learning.",
    "No prior expertise in integer programming, solver engineering, or LLM training required.",
  ],
  references: [
    { key: "AhmadiTeshnizi et al., 2024", topic: "Formulation", title: "OptiMUS: Scalable Optimization Modeling with (MI)LP Solvers and Large Language Models", venue: "ICML 2024" },
    { key: "Astorga et al., 2025", topic: "Formulation", title: "Autoformulation of Mathematical Optimization Models Using LLMs", venue: "ICML 2025" },
    { key: "Xiao et al., 2023", topic: "Formulation", title: "Chain-of-Experts: When LLMs Meet Complex Operations Research Problems", venue: "ICLR 2023" },
    { key: "Huang et al., 2025", topic: "Formulation", title: "ORLM: A Customizable Framework in Training Large Models for Automated Optimization Modeling", venue: "Operations Research 2025" },
    { key: "Jiang et al., 2025", topic: "Formulation", title: "LLMOPT: Learning to Define and Solve General Optimization Problems from Scratch", venue: "ICLR 2025" },
    { key: "Liang et al., 2026", topic: "Formulation", title: "Large-Scale Optimization Model Auto-Formulation: Harnessing LLM Flexibility via Structured Workflow", venue: "arXiv 2026" },
    { key: "Xing et al., 2024", topic: "Evaluation", title: "Towards Human-Aligned Evaluation for Linear Programming Word Problems", venue: "LREC-COLING 2024" },
    { key: "Zhai et al., 2025", topic: "Evaluation", title: "EquivaMap: Leveraging LLMs for Automatic Equivalence Checking of Optimization Formulations", venue: "ICML 2025" },
    { key: "Lawless et al., 2025", topic: "Solving", title: "LLMs for Cold-Start Cutting Plane Separator Configuration", venue: "CPAIOR 2025" },
    { key: "Yang et al.", topic: "Discovery", title: "Large Language Models as Optimizers", venue: "ICLR" },
    { key: "Wu et al., 2024", topic: "Discovery", title: "Large Language Model-Enhanced Algorithm Selection: Towards Comprehensive Algorithm Representation", venue: "IJCAI 2024" },
    { key: "Pan et al., 2025", topic: "Discovery", title: "LLM-TPF: Multiscale Temporal Periodicity-Semantic Fusion LLMs for Time Series Forecasting", venue: "IJCAI 2025" },
    { key: "Liu et al., 2024", topic: "Discovery", title: "Evolution of Heuristics (EoH): Towards Efficient Automatic Algorithm Design Using LLMs", venue: "ICML 2024" },
    { key: "Ye et al., 2024", topic: "Discovery", title: "ReEvo: Large Language Models as Hyper-Heuristics with Reflective Evolution", venue: "NeurIPS 2024" },
    { key: "Van Stein & Bäck, 2024", topic: "Discovery", title: "Llamea: A Large Language Model Evolutionary Algorithm for Automatically Generating Metaheuristics", venue: "IEEE TEVC 2024" },
    { key: "Dat et al., 2025", topic: "Discovery", title: "HSEvo: Elevating Automatic Heuristic Design with Diversity-Driven Harmony Search and Genetic Algorithm Using LLMs", venue: "AAAI 2025" },
    { key: "Yao et al., 2025", topic: "Discovery", title: "Multi-Objective Evolution of Heuristics Using Large Language Models", venue: "AAAI 2025" },
    { key: "Hu et al., 2026", topic: "Discovery", title: "Multimodal LLM-Assisted Evolutionary Search for Programmatic Control Policies", venue: "ICLR 2026" },
    { key: "Liu et al., 2026", topic: "Survey", title: "A Systematic Survey on Large Language Models for Algorithm Design", venue: "ACM Computing Surveys 2026" },
    { key: "Conforti et al., 2014", topic: "Background", title: "Integer Programming", venue: "Springer" },
  ],
  history: [
    { year: "2026 · Jan", name: "AAAI 2026 Tutorial", detail: "Preliminary version delivered, ~200 attendees.", link: "https://conlaw.github.io/llm_opt_tutorial/tutorial.html" },
    { year: "2025", name: "CEC 2025 · IJCCI 2025 · IEEE Web Seminar", detail: "Invited talks on automated algorithm design with LLMs; materials online.", link: "https://cis.taskforce.ieee.org/esco/webinar-series/esco-webinar-26/" },
    { year: "2026 · Aug", name: "IJCAI 2026 Tutorial", detail: "Expanded version with algorithmic discovery track.", link: null },
  ],
};
