// Tutorial data IJCAI 2026
const PAPER_LINK_PLACEHOLDER = "TODO_ADD_PAPER_LINK_HERE";
window.TUTORIAL_DATA = {
  meta: {
    venue: "IJCAI 2026",
    city: "Bremen, Germany",
    dates: "August 15 - 17, 2026",
    length: "Half day 3 hours 30 minutes"
  },
  presenters: [
    {
      name: "Connor Lawless",
      affiliation: "Stanford University",
      email: "lawlessc@stanford.edu",
      link: "https://conlaw.github.io/",
      photo: "figures/connor_headshot.jpeg",
      blurb: "Human-Centered AI postdoctoral researcher at Stanford, with a PhD in Operations Research and Information Engineering from Cornell. His work blends machine learning, computational optimization, and human鈥揷omputer interaction to create human-centered artificial intelligence.",
    },
    {
      name: "Fei Liu",
      affiliation: "University of Zurich & ETH Zurich",
      email: "fei.liu2@uzh.ch",
      link: "https://feiliu36.github.io/",
      photo: "figures/Fei-Liu.png",
      blurb: "Postdoctoral researcher at UZH & ETH Zurich. Works on automated algorithm design, evolutionary algorithms, neural combinatorial optimization, and multiobjective optimization. Lead author on [LLM4AD](https://github.com/Optima-CityU/LLM4AD).",
    },
    {
      name: "Hanzhang Qin",
      affiliation: "National University of Singapore",
      email: "hzqin@nus.edu.sg",
      link: "https://hanzhangqin.com/",
      photo: "figures/hanzhang_qin.png",
      blurb: "Assistant Professor at NUS. Operations researcher working on optimization, revenue management, and the application of large language models to large-scale optimization workflows.",
    },
    {
      name: "Ellen Vitercik",
      affiliation: "Stanford University",
      email: "vitercik@stanford.edu",
      link: "https://vitercik.github.io/",
      photo: "figures/ellen_headshot.jpg",
      blurb: "Assistant Professor at Stanford with a joint appointment between the Management Science & Engineering and Computer Science departments. Her research鈥攚hich has been recognized with a Schmidt Sciences AI2050 Early Career Fellowship and an NSF CAREER award, among other honors鈥攕pans machine learning and discrete optimization.",
    },
  ],
  schedule: [
    {
      id: "intro",
      part: "Part 1",
      title: "Introduction",
      duration: "15 min",
      minutes: 15,
      speaker: "All",
      blurb: "A broad overview of mathematical optimization, centered on mixed integer linear programming (MILP) as a core AI and OR technique.",
      bullets: [
        "The optimization pipeline: understand, formulate, tune, validate.",
        "Where current bottlenecks lie, and where LLMs can help.",
        "Framing the two halves of the tutorial: copilot + discovery.",
      ],
    },
    {
      id: "formulation",
      part: "Part 2",
      title: "Optimization Model Formulation",
      duration: "45 min",
      minutes: 45,
      speaker: ".",
      blurb: "Translating informal problem descriptions into precise optimization models, a central bottleneck for domain experts without formal training in optimization.",
      bullets: [
        "Agentic frameworks: OptiMUS, LEAN-LLM-OPT, Chain-of-Experts, MCTS-based approaches.",
        "Fine-tuned models specialized for optimization: ORLM, LLM-OPT.",
        "Benchmark datasets: textbook-style, synthetic, and real-world collections such as IndustryOR.",
      ],
    },
    {
      id: "evaluation",
      part: "Part 3",
      title: "Optimization Model Evaluation",
      duration: "30 min",
      minutes: 30,
      speaker: ".",
      blurb: "How do we know a generated formulation actually solves the right problem? Recent frameworks for assessing correctness and equivalence.",
      bullets: [
        "Graph-isomorphism-based approaches.",
        "Execution-based accuracy metrics.",
        "EquivaMap: formal equivalence checking.",
      ],
    },
    {
      id: "break",
      part: "Break",
      title: "Coffee Break",
      duration: "30 min",
      minutes: 30,
      speaker: null,
      blurb: null,
      bullets: [],
    },
    {
      id: "solving",
      part: "Part 4",
      title: "Optimization Model Solving",
      duration: "45 min",
      minutes: 45,
      speaker: ".",
      blurb: "Modern solvers (Gurobi, CPLEX) expose many configuration parameters whose tuning is time-consuming even for experts. Can LLMs help?",
      bullets: [
        "LLMs leveraging documentation, code, and prior research for cold-start configuration.",
        "Contrast with traditional data-driven configuration methods.",
        "Strengths, limitations, and open challenges in deployment.",
      ],
    },
    {
      id: "discovery",
      part: "Part 5",
      title: "Algorithmic Design with LLMs",
      duration: "45 min",
      minutes: 45,
      speaker: ".",
      blurb: "LLMs as a new paradigm for automating algorithm design 鈥?lowering the barrier to entry and exploring design spaces hard to navigate manually.",
      bullets: [
        "A taxonomy: LLM as optimizer, LLM as extractor, LLM as predictor, LLM as designer.",
        "Methods: EoH, ReEvo, Llamea, HSEvo, MEoH, MLES, EoH-S, MoH.",
        "Applications across combinatorial optimization, black-box optimization, ML, and scientific discovery.",
        "Open challenges.",
      ],
    },
  ],
  objectives: [
    "Understand the core optimization pipeline and where LLMs can intervene.",
    "Survey the state of the art in LLM-based auto-formulation, from prompting to fine-tuning to agentic systems.",
    "Reason about correctness and equivalence for LLM-generated optimization models.",
    "Recognize how LLMs can assist solver configuration without large training datasets.",
    "Map the taxonomy of LLM-driven algorithmic discovery and its open research directions.",
  ],
  audiences: [
    {
      tag: "AI researchers",
      blurb: "Graduate students and researchers with little or no formal background in optimization.",
    },
    {
      tag: "OR researchers",
      blurb: "Optimization and operations research researchers curious about how LLMs can assist modeling and algorithm design.",
    },
    {
      tag: "Practitioners",
      blurb: "Builders of AI-enabled decision-support systems in logistics, planning, scheduling, and resource allocation.",
    },
  ],
  prerequisites: [
    "Basic mathematical maturity (variables, constraints, functions).",
    "General exposure to modern AI / machine learning.",
    "No prior expertise in integer programming, solver engineering, or LLM training required.",
  ],
  references: [
    { key: "AhmadiTeshnizi et al., 2024", topic: "Formulation", title: "OptiMUS: Scalable Optimization Modeling with MILP Solvers and Large Language Models", venue: "ICML 2024", link: "https://arxiv.org/abs/2402.10172" },
    { key: "Zhai et al., 2025", topic: "Formulation", title: "EquivaMap: Leveraging LLMs for Automatic Equivalence Checking of Optimization Formulations", venue: "ICML 2025", link: "https://arxiv.org/abs/2502.14760" },
    { key: "Astorga et al., 2025", topic: "Formulation", title: "Autoformulation of Mathematical Optimization Models Using LLMs", venue: "ICML 2025", "https://arxiv.org/abs/2411.01679" },
    { key: "Xiao et al., 2023", topic: "Formulation", title: "Chain-of-Experts: When LLMs Meet Complex Operations Research Problems", venue: "ICLR 2023", link: "https://openreview.net/forum?id=HobyL1B9CZ" },
    { key: "Huang et al., 2025", topic: "Formulation", title: "ORLM: A Customizable Framework in Training Large Models for Automated Optimization Modeling", venue: "Operations Research 2025", link: "https://pubsonline.informs.org/doi/abs/10.1287/opre.2024.1233" },
    { key: "Jiang et al., 2025", topic: "Formulation", title: "LLMOPT: Learning to Define and Solve General Optimization Problems from Scratch", venue: "ICLR 2025", link: "https://arxiv.org/abs/2410.13213" },
    { key: "Liang et al., 2026", topic: "Formulation", title: "Large-Scale Optimization Model Auto-Formulation: Harnessing LLM Flexibility via Structured Workflow", venue: "arXiv 2026", link: "https://arxiv.org/abs/2601.09635" },
    { key: "Xing et al., 2024", topic: "Evaluation", title: "Towards Human-Aligned Evaluation for Linear Programming Word Problems", venue: "LREC-COLING 2024", link: "https://aclanthology.org/2024.lrec-main.1438/" },
    { key: "Zhai et al., 2025", topic: "Evaluation", title: "EquivaMap: Leveraging LLMs for Automatic Equivalence Checking of Optimization Formulations", venue: "ICML 2025", link: "https://arxiv.org/abs/2502.14760" },
    { key: "Lawless et al., 2025", topic: "Solving", title: "LLMs for Cold-Start Cutting Plane Separator Configuration", venue: "CPAIOR 2025", link: "https://link.springer.com/chapter/10.1007/978-3-031-95976-9_4" },
    { key: "Liu et al., 2024", topic: "Algorithm Design", title: "Evolution of Heuristics (EoH): Towards Efficient Automatic Algorithm Design Using LLMs", venue: "ICML 2024", link: "https://openreview.net/forum?id=BwAkaxqiLB" },
    { key: "Ye et al., 2024", topic: "Algorithm Design", title: "ReEvo: Large Language Models as Hyper-Heuristics with Reflective Evolution", venue: "NeurIPS 2024", link: "https://proceedings.neurips.cc/paper_files/paper/2024/hash/4ced59d480e07d290b6f29fc8798f195-Abstract-Conference.html" },
    { key: "Van Stein & Back, 2024", topic: "Algorithm Design", title: "Llamea: A Large Language Model Evolutionary Algorithm for Automatically Generating Metaheuristics", venue: "IEEE TEVC 2024", link: "https://ieeexplore.ieee.org/abstract/document/10752628" },
    { key: "Dat et al., 2025", topic: "Algorithm Design", title: "HSEvo: Elevating Automatic Heuristic Design with Diversity-Driven Harmony Search and Genetic Algorithm Using LLMs", venue: "AAAI 2025", link: "https://ojs.aaai.org/index.php/AAAI/article/view/34898" },
    { key: "Yao et al., 2025", topic: "Algorithm Design", title: "Multi-Objective Evolution of Heuristics Using Large Language Models", venue: "AAAI 2025", link: "https://ojs.aaai.org/index.php/AAAI/article/view/34922" },
    { key: "Hu et al., 2026", topic: "Algorithm Design", title: "Multimodal LLM-Assisted Evolutionary Search for Programmatic Control Policies", venue: "ICLR 2026", link: "https://arxiv.org/abs/2508.05433" },
    { key: "Liu et al., 2026", topic: "Algorithm Design", title: "EoH-S: Evolution of Heuristic Set Using LLMs for Automated Heuristic Design", venue: "AAAI 2026", link: "https://ojs.aaai.org/index.php/AAAI/article/view/41038" },
    { key: "Shi et al., 2026", topic: "Algorithm Design", title: "Generalizable Heuristic Generation Through Large Language Models with Meta-Optimization", venue: "ICLR 2026", link: "https://arxiv.org/abs/2505.20881" },
    { key: "Liu et al., 2026", topic: "Survey", title: "A Systematic Survey on Large Language Models for Algorithm Design", venue: "ACM Computing Surveys 2026", link: "https://arxiv.org/abs/2410.14716" },
    { key: "Xiao et al., 2026", topic: "Survey", title: "A Survey of Optimization Modeling Meets LLMs: Progress and Future Directions", venue: "arXiv 2025", link: "https://arxiv.org/abs/2508.10047" },
    { key: "Conforti et al., 2014", topic: "Background", title: "Integer Programming", venue: "Springer", link: PAPER_LINK_PLACEHOLDER },
  ],
  history: [
    { year: "2026", name: "AAAI 2026 Tutorial", detail: "Preliminary version delivered, ~200 attendees.", link: "https://conlaw.github.io/llm_opt_tutorial/tutorial.html" },
    { year: "2025", name: "CEC 2025  IJCCI 2025  IEEE Web Seminar", detail: "Invited talks on automated algorithm design with LLMs; materials online.", link: "https://cis.taskforce.ieee.org/esco/webinar-series/esco-webinar-26/" },
    { year: "2026", name: "IJCAI 2026 Tutorial", detail: "Expanded version with algorithmic discovery track.", link: null },
  ],
};

